name: Publish to Medium

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/src/content/blog/*.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @medium/sdk gray-matter

      - name: Publish to Medium
        env:
          # TODO(Matt): Add these secrets to your GitHub repository
          MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}
          MEDIUM_USER_ID: ${{ secrets.MEDIUM_USER_ID }}
        run: |
          for file in frontend/src/content/blog/*.md; do
            if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^$file$"; then
              node .github/scripts/publish-to-medium.js "$file"
            fi
          done 